name: Wattspeed

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Wattspeed Action
        uses: Caphyon/wattspeed-action@v1
        with:
          # [required]
          # Get the token from the webpage settings
          # inside your Wattspeed account
          token: "Govb7ob4noJ1NHc7+zigx9ZUwU91HYbZ8AaRSn4zNz3AR8xY8N7IMWatiWEraPTA"
